import Head from 'next/head'
import Image from 'next/image'
import { Inter, Fira_Code } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const FiraCode = Fira_Code({
  weight: '400',
  subsets: ['latin']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Farid Darmaji ~ Test Emtrade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={`text-3xl font-bold ${FiraCode.className}`}>
          Hello world!
        </h1>
      </main>
    </>
  )
}
