import Head from 'next/head'
import Image from 'next/image'
import { Inter, Fira_Code } from 'next/font/google'
import { 
  Navbar, 
  Title, 
  Description,  
  EventInformation, 
  Button, 
  Banner,
  EventDetail,
  Checkout
} from '@/components/index.d'

const FiraCode = Fira_Code({
  weight: '400',
  subsets: ['latin']
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Farid Darmaji ~ Test Emtrade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full flex justify-center bg-neutral-100'>
        <div className='w-full max-w-[720px] flex flex-col bg-white'>
          <Navbar name="Bedah Emiten TOWR" />
          
          <div className='pt-6 xs:px-6 bg-cs-black xs:bg-white mb-6'>
            <Banner 
              src="https://staging-emtrade.s3.ap-southeast-1.amazonaws.com/event/Event_Mock.png" 
            />
          </div>
          <div className='w-full flex flex-col px-6'>
            <Title costumeClass="mb-6">
              Bedah Emiten TOWR PT Sarana Menara Nusantara TBK.
            </Title>
            <EventDetail 
              date="Jumat, 16 Juli 2021" 
              time="16:00 - 17:00 WIB" 
              location="Webinar via Zoom"
              costumeClass="mb-6"
            />
            <Description costumeClass="mb-4">
              EMITALK merupakan special webinar yang menghadirkan pembicara dari emiten saham untuk memberikan pemahaman secara lebih mendalam kepada oara investor saham tentang kinerja dan kondisi terkini perusahaan.
            </Description>
            <Description costumeClass="mb-4">
              Pada kesempatan ini Emitalk berkolaborasi dengan PT Kalbe Farma TBK yang akan membahas kondisi dan kinerja terkini KLBF.
            </Description>
            <Description costumeClass="mb-4">
              Rincian acara Emitalk: Menuju Indonesia Sehat adalah sebagai berikut:
            </Description>
            <Description costumeClass="mb-4">
              Hari, Tanggal : Jumat, 16 Juli 2021
              Waktu : 16:00 - 17:00
              Tema :KLBF menju indonesia sehat
            </Description>
            <Description costumeClass="mb-4">
              Narasumber : Bernadus K. Winata, Direktur PT Kalbe Farma, TBK
            </Description>
            <Description costumeClass="mb-4">
              Platform : Webinar via Zoom
            </Description>
            <Description costumeClass="mb-4">
              Happy Learning, Happy Investing!
            </Description>
          </div>
          
          <Checkout discount={10} price={150000} total_price={110000} />
        </div>
      </div>
    </>
  )
}
